# Laboratorio 2
## Algoritmos de Aprendizaje no Supervisado

Universidad del Valle de Guatemala  
Facultad de Ingeniería  
Departamento de Ciencias de la Computación  
CC3074– Minería de Datos  
Semestre I – 2026

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Clustering
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics import silhouette_score, silhouette_samples
from scipy.cluster.hierarchy import dendrogram, linkage

# Hopkins
from pyclustertend import hopkins

# PCA
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from factor_analyzer.factor_analyzer import calculate_kmo, calculate_bartlett_sphericity

# Reglas de Asociación
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder

print("Todo importado correctamente")

Todo importado correctamente

In [6]:
# Cargar el dataset
df = pd.read_csv("movies_2026.csv", encoding="latin-1")

# Vista general
print("Shape:", df.shape)
print("\nPrimeras filas:")
df.head()

Shape: (19883, 28)

Primeras filas:

,id,budget,genres,homePage,productionCompany,productionCompanyCountry,productionCountry,revenue,runtime,video,...,releaseDate,voteAvg,voteCount,genresAmount,productionCoAmount,productionCountriesAmount,actorsAmount,castWomenAmount,castMenAmount,releaseYear
0,1627085,0.0,Drama|Crime,NaN,NaN,NaN,NaN,0.0,95,False,...,2026-02-01,0.0,0,2,0,0,8,2.0,5.0,2026.0
1,1626914,0.0,Animation,NaN,NaN,NaN,NaN,0.0,3,False,...,2026-02-01,0.0,0,1,0,0,4,0.0,0.0,2026.0
2,1626898,0.0,Animation,NaN,NaN,NaN,NaN,0.0,2,False,...,2026-02-01,0.0,0,1,0,0,3,0.0,0.0,2026.0
3,1626808,0.0,Thriller|Mystery|Documentary,NaN,NaN,NaN,NaN,0.0,5,False,...,2026-02-01,0.0,0,3,0,0,7,0.0,0.0,2026.0
4,1626678,0.0,Animation,NaN,NaN,NaN,NaN,0.0,12,False,...,2026-02-01,0.0,0,1,0,0,3,0.0,0.0,2026.0

In [7]:
# Tipos de datos y nulos
print("Tipos de datos y valores nulos")
print(df.dtypes)
print("\nValores nulos por columna")
print(df.isnull().sum().sort_values(ascending=False))

Tipos de datos y valores nulos
id                             int64
budget                       float64
genres                           str
homePage                         str
productionCompany                str
productionCompanyCountry         str
productionCountry                str
revenue                      float64
runtime                        int64
video                         object
director                         str
actors                           str
actorsPopularity                 str
actorsCharacter                  str
originalTitle                    str
title                            str
originalLanguage                 str
popularity                   float64
releaseDate                      str
voteAvg                      float64
voteCount                      int64
genresAmount                   int64
productionCoAmount             int64
productionCountriesAmount      int64
actorsAmount                   int64
castWomenAmount              float64
castMenAmount                float64
releaseYear                  float64
dtype: object

Valores nulos por columna
homePage                     14276
productionCompanyCountry      8410
productionCompany             5660
productionCountry             3874
actorsCharacter               2835
actorsPopularity              2608
actors                        2601
genres                        1965
director                       976
video                          486
castMenAmount                  162
castWomenAmount                 37
releaseDate                      2
releaseYear                      2
title                            1
originalTitle                    1
runtime                          0
revenue                          0
budget                           0
id                               0
voteAvg                          0
popularity                       0
originalLanguage                 0
voteCount                        0
productionCountriesAmount        0
productionCoAmount               0
genresAmount                     0
actorsAmount                     0
dtype: int64

In [8]:
# Estadísticas descriptivas de variables numéricas
df.describe()

,id,budget,revenue,runtime,popularity,voteAvg,voteCount,genresAmount,productionCoAmount,productionCountriesAmount,actorsAmount,castWomenAmount,castMenAmount,releaseYear
count,1.988300e+04,1.988300e+04,1.988300e+04,19883.000000,19883.000000,19883.000000,19883.000000,19883.000000,19883.000000,19883.000000,19883.000000,19846.000000,19721.000000,19881.000000
mean,9.022402e+05,9.413280e+06,2.879213e+07,66.093799,26.248842,3.837069,675.927325,1.949253,1.972539,1.230247,1082.049640,3516.505996,8224.352061,2016.827222
std,6.848978e+05,2.774781e+07,1.109805e+08,50.089055,156.067177,3.397705,1938.194656,1.256225,2.312075,2.244688,26402.818732,47768.661984,71257.943156,12.838005
min,5.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1902.000000
25%,1.462195e+05,0.000000e+00,0.000000e+00,10.000000,0.054600,0.000000,0.000000,1.000000,0.000000,1.000000,3.000000,0.000000,0.000000,2013.000000
50%,8.696230e+05,0.000000e+00,0.000000e+00,86.000000,8.502000,5.400000,6.000000,2.000000,1.000000,1.000000,9.000000,2.000000,3.000000,2021.000000
75%,1.589602e+06,1.000000e+06,3.306335e+05,103.000000,22.239000,6.800000,423.000000,3.000000,3.000000,1.000000,21.000000,6.000000,12.000000,2025.000000
max,1.627166e+06,3.800000e+08,2.847246e+09,750.000000,11474.647000,10.000000,30788.000000,16.000000,89.000000,155.000000,919590.000000,922162.000000,922017.000000,2026.000000